import textwrap
from PIL import Image, ImageDraw, ImageFont
from text_utils import clean_text_for_image, shorten_text


def generate_flyer(event: dict, qr_path: str, output_path: str) -> None:
    """
    Generate an A4-style flyer/poster as a PNG image.
    """
    width, height = 1240, 1754  # Approx. A4 ratio at medium resolution

    image = Image.new("RGB", (width, height), color=(255, 255, 255))
    draw = ImageDraw.Draw(image)

    try:
        title_font = ImageFont.truetype("arial.ttf", 68)
        heading_font = ImageFont.truetype("arial.ttf", 42)
        body_font = ImageFont.truetype("arial.ttf", 34)
        small_font = ImageFont.truetype("arial.ttf", 28)
    except:
        title_font = ImageFont.load_default()
        heading_font = ImageFont.load_default()
        body_font = ImageFont.load_default()
        small_font = ImageFont.load_default()

    description = clean_text_for_image(event["description"])
    description = shorten_text(description, 450)  # Limit text length

    # Header
    draw.rectangle((0, 0, width, 220), fill=(20, 90, 160))
    draw.text((80, 75), "Digital Learning Campus", fill="white", font=heading_font)

    # Title
    y = 300
    wrapped_title = textwrap.wrap(event["title"], width=26)
    for line in wrapped_title:
        draw.text((80, y), line, fill=(20, 20, 20), font=title_font)
        y += 82

    # Event information box
    y += 40
    box_top = y
    box_bottom = y + 300
    draw.rounded_rectangle(
        (80, box_top, width - 80, box_bottom),
        radius=25,
        outline=(210, 210, 210),
        width=3,
        fill=(245, 247, 250),
    )

    info_y = y + 45
    draw.text((120, info_y), f"Date: {event['date']}", fill=(40, 40, 40), font=body_font)
    info_y += 60
    draw.text((120, info_y), f"Time: {event['time']}", fill=(40, 40, 40), font=body_font)
    info_y += 60
    draw.text((120, info_y), f"Location: {event['location']}", fill=(40, 40, 40), font=body_font)
    info_y += 60
    draw.text(
        (120, info_y),
        f"Level: {event['level']} | Language: {event['language']}",
        fill=(40, 40, 40),
        font=body_font,
    )

    # Description
    y = box_bottom + 80
    draw.text((80, y), "About this learning offer", fill=(20, 20, 20), font=heading_font)
    y += 70

    wrapped_desc = textwrap.wrap(description, width=55)
    for line in wrapped_desc[:7]:  #If the text is too long, you can adjust the line limit.
        draw.text((80, y), line, fill=(70, 70, 70), font=body_font)
        y += 48

    # QR code section
    qr = Image.open(qr_path).resize((260, 260))
    image.paste(qr, (80, height - 390))

    draw.text(
        (380, height - 330),
        "Scan the QR code",
        fill=(20, 20, 20),
        font=heading_font,
    )
    draw.text(
        (380, height - 270),
        "Open the DLC learning offer page",
        fill=(80, 80, 80),
        font=body_font,
    )

    # Footer
    draw.rectangle((0, height - 80, width, height), fill=(20, 90, 160))
    draw.text((80, height - 58), "Generated by DLC Press Kit Builder Prototype", fill="white", font=small_font)

    image.save(output_path)